name: NoBadWord
main: ca.unex.nobadword.Main
version: 1.1.5
description: >
             UnexCraft official AntiSwear plugin
commands:
  badword:
    description: Adds a badword to the blacklist
  badwords:
    description: List words you shouldn't say!